[presense]
pipresense ansible_host=pipresense.local

[plc4go]
piplc4go ansible_host=piplc4go.local

[sense]
pisense ansible_host=pisense.local

[lense]
pilense ansible_host=pilense.local

[otio_cluster:children]
presense
plc4go
sense
lense

[otio_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
