apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otio.prefix" . }}-otio-credentials
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.credentials.postgresDatabase | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.credentials.rabbitmqUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.credentials.rabbitmqPassword | quote }}
  LAB_AMQP_URL: {{ include "otio.amqpURL" . | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otio.prefix" . }}-sense-config
type: Opaque
stringData:
  config.json: |
    {{- include "otio.senseConfig" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otio.prefix" . }}-lense-topology
data:
  topology.json: |
    {{- include "otio.topology" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otio.prefix" . }}-mosquitto-config
data:
  mosquitto.conf: |
    {{- .Files.Get "files/mosquitto.conf" | nindent 4 }}
