(function(){
 'use strict';
 function mount(){
  const panel=document.getElementById('page-certificates');if(!panel)return;
  panel.innerHTML='<div class="card"><h2>Certificates</h2><p>OPC UA application identity and trusted server certificate. Profiles are stored on the Protocol Lab gateway and selected per connection.</p><form id="certificateForm"><div class="config-fields"><label>Profile name<input name="id" required pattern="[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}" placeholder="plant-opcua"></label><label>Client certificate · PEM<input name="certificate" type="file" accept=".pem,.crt" required></label><label>Client private key · PEM<input name="privateKey" type="file" accept=".pem,.key" required></label><label>Trusted server certificate · PEM<input name="serverCertificate" type="file" accept=".pem,.crt" required></label><label>Configuration token (if required)<input name="token" type="password" autocomplete="off"></label></div><p class="k">Basic256Sha256 / SignAndEncrypt; RSA ≥2048 bits. Client certificate must contain its Application URI. Uploading an existing profile name replaces it. Private keys are never returned by this UI. The server must trust the client certificate.</p><button type="submit">Upload / replace profile</button></form><p id="certificateResult" role="status"></p><div id="certificateList"></div></div>';
  const banner=document.createElement('div');banner.id='certificateWarning';banner.setAttribute('role','alert');banner.hidden=true;banner.style.cssText='background:#671f2c;color:#fff;padding:12px 18px;margin-bottom:12px;border-radius:8px';document.querySelector('main').prepend(banner);
  const api='/protocol-lab/api/certificates',output=document.getElementById('certificateResult'),list=document.getElementById('certificateList');
  async function refresh(){try{const r=await fetch(api,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Certificate service unavailable');list.replaceChildren();if(data.enabled&&!data.items?.length)list.textContent='No certificate profiles uploaded yet.';if(!data.enabled)output.textContent='Persistent certificate storage is not configured on Protocol Lab. Set OTIO_CERTIFICATE_DIR and mount a persistent volume.';for(const item of data.items||[]){const row=document.createElement('p');row.textContent=item.id+' · '+item.purpose+' · client expires '+new Date(item.clientExpires).toLocaleDateString()+' · server expires '+new Date(item.serverExpires).toLocaleDateString();row.title='Trusted server SHA-256: '+item.serverFingerprint;list.append(row);}const expiring=(data.items||[]).filter(c=>!c.valid||c.daysRemaining<=30);banner.hidden=!expiring.length;banner.replaceChildren();if(expiring.length){const link=document.createElement('a');link.href='#certificates';link.style.color='inherit';link.textContent='Certificate action required: '+expiring.map(c=>c.id+(!c.valid?' — expired or not yet valid':' — expires in '+c.daysRemaining+' days')).join('; ');banner.append(link);}}catch(e){output.textContent=e.message;banner.hidden=false;banner.textContent='Certificate monitoring unavailable: '+e.message;}}
  document.getElementById('certificateForm').onsubmit=async event=>{event.preventDefault();const form=event.target,button=form.querySelector('button');button.disabled=true;try{const body={id:form.elements.id.value.trim()};for(const name of ['certificate','privateKey','serverCertificate']){const file=form.elements[name].files[0];if(!file||file.size>65536)throw Error(name+': choose a PEM file no larger than 64 KiB');body[name]=await file.text();}const r=await fetch(api,{method:'PUT',headers:{'Content-Type':'application/json','X-OTIO-Config-Token':form.elements.token.value},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Upload failed');form.reset();output.textContent='Profile saved. Select it in Protocol Lab → OPC UA. Existing references use the replacement on the next read.';await refresh();}catch(e){output.textContent=e.message;}finally{button.disabled=false;}};
  refresh();setInterval(refresh,60000);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
