apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otio
resources:
  - namespace.yaml
  - storage.yaml
  - services.yaml
  - workloads.yaml
configMapGenerator:
  - name: sense-config
    files: [config.json=config/sense.json]
  - name: lense-topology
    files: [topology.json=config/topology.json]
  - name: mosquitto-config
    files: [mosquitto.conf=config/mosquitto.conf]
